name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2

      - name: convert notebooks and word docs to posts
        uses: fastai/fastpages@master
        with:
          BOOL_SAVE_MARKDOWN: false
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}

      - uses: helaili/jekyll-action@2.0.1
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}